#:schema https://golangci-lint.run/jsonschema/golangci.jsonschema.json

version = "2"

[formatters]
enable = ["goimports", "gofumpt"]

[formatters.settings.gofumpt]
module-path = "github.com/4evy/dis"

[formatters.settings.goimports]
local-prefixes = ["github.com/4evy/dis"]

[linters]
enable = [
  "bodyclose",
  "dupl",
  "durationcheck",
  "errorlint",
  "exptostd",
  "goconst",
  "gocritic",
  "ineffassign",
  "makezero",
  "misspell",
  "mnd",
  "modernize",
  "perfsprint",
  "prealloc",
  "staticcheck",
  "unparam",
  "unused",
  "usestdlibvars",
  "wastedassign",
]

[linters.exclusions]
paths = ["node_modules"]
